### ISSUE TITLE
`bc` is required for `curlbar`

### ISSUE THREAD

**Issue by indrakaw** [Szero/volaupload.sh#2]
It requires `bc` to run `curlbar`. Most of Linux dist doesn't have this installed. You should add this to prerequisites list too.

**Comment by szero** [comment]
Updated in 8c6fff8

**Comment by indrakaw** [comment]
`install.sh` force me to install `curlbar`. It would be great if there is kind of check, e.g. is `bc` installed? Fix this too.

**Comment by szero** [comment]
0d48b19 install script will now ask you if you want curlbar and check if bc is installed.
