### ISSUE TITLE
Volafile support for stuff2vola.sh

### ISSUE THREAD

**Issue by indrakaw** [Szero/volaupload.sh#3]
Normally, to download a file from Volafile via `wget`, I use this:
```
wget --no-cookies --header "Cookie: allow-download=1" "https://volafile.org/get/ABCDEFGH/filename.zip
```

**Comment by szero** [comment]
Some justification for that? If file is already on volafile you can just link it in chat in any room and it will expand into a download button.

**Comment by indrakaw** [comment]
But what if you want to reupload because the original file's life time is only in minutes? 🤔

Passing user cookies to `wget` or `curl` is fine too, because non-pro users has limited download speed.

**Comment by szero** [comment]
Added this in here 0d48b19. If you have volafile pro, please check if you have faster download speeds because I have no way to check that.
