### ISSUE TITLE
Automatically deletes uploaded file.

### ISSUE THREAD

**Issue by indrakaw** [Szero/volaupload.sh#5]
Let's have an example case:
FBI is raiding my house and I have to upload a whole folder into Vola. ASAP. 
```
volaupload.sh ~/Pictures/2018-26-8/
```
There are about 80 files.
Is there a way to delete uploaded files without wait until whole progress done then delete?

**Comment by szero** [comment]
I added this here f000d54 
if you will specify the `-v` option, each file in the directory will be removed as soon as its uploaded. The command also removes the directories.
