### ISSUE TITLE
Unable upload via volaupload.sh files greater than a few hundred megabytes

### ISSUE THREAD

**Issue by dimetime** [Szero/volaupload.sh#8]
For some time now, regardless of the server one is uploading to, 7 - 10, when trying to upload with volaupload.sh, latest or the older variations, from sizes of a few hundred megabytes up to the maximum of 20 gigabytes, volaupload.sh is randomly halting upload to curl error 22 or 52:

`$ bash volaupload.sh -r 1bmweqm3c 600
</\> Uploading 600 to 1bmweqm3c, dl9 as Volaphile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 50  600M    0     0   50  303M      0  5146k  0:01:59  0:01:00  0:00:59 7184k
curl: (22) The requested URL returned error: 502 Service Unavailable

</\> Uploading 600 to 1bmweqm3c, dl7 as Volaphile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 58  600M    0     0   58  350M      0  5954k  0:01:43  0:01:00  0:00:43 6108k
curl: (52) Empty reply from server

</\> Uploading 600 to 1bmweqm3c, dl9 as Volaphile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 41  600M    0     0   41  251M      0  4279k  0:02:23  0:01:00  0:01:23 4214k
curl: (52) Empty reply from server
`

**Comment by szero** [comment]
Thanks for the report, this is the issue on the server side, basically server cancels any uploads which take longer than one minute to finish and my script doesn't have resume logic to continue the upload. In the mean time while I'm trying to find solution for the script, [heres](https://github.com/volafiled/node-volaupload) working uploader written in javascript that has resume logic implemented.

**Comment by szero** [comment]
@dimetime I've added upload resume support in [this](https://github.com/szero/volascripts.sh/commit/690f324666b888b95525c6334deb3e857455a927) commit, also please have [this](https://github.com/szero/volascripts.sh/commit/690f324666b888b95525c6334deb3e857455a927#r40486258) note in mind  while trying to upload large files.

**Comment by szero** [comment]
Hey again, @dimetime. I've updated the script after finding out why it was not working for you. I have been testing it only with my curl wrapper script `curlbar` and didn't test it with plain `curl` and it wasn't returning proper error codes. Now it should be good to go for you.
